#!/bin/sh

APPDIR=`dirname $0`;

if [ -z "$GWT_CLASSPATH" ]; then
  echo 'ERROR: $GWT_CLASSPATH is not set'
  echo 'Set $GWT_CLASSPATH to point to the GWT JAR files. For example:'
  echo 'export GWT_DIR="/Users/bringert/src/gwt-mac-1.5.2"'
  echo 'export GWT_CLASSPATH="$GWT_DIR/gwt-user.jar:$GWT_DIR/gwt-dev-mac.jar"'
  exit 1
fi

# HACK: the dnd thing
PGF_CLASSPATH="$GF_LIB_PATH/../lib/java/gf-gwt.jar:$GF_LIB_PATH/../src/server/gwt/lib/gwt-dnd-2.5.6.jar"

java -XstartOnFirstThread -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:$PGF_CLASSPATH:$GWT_CLASSPATH" com.google.gwt.dev.GWTShell -out "$APPDIR/www" -noserver "$@" http://localhost:1970/;
